config/routes.rb
Rails.application.routes.draw do

  root 'dashboards#index'
  
  resources :dashboards do
    member do
      get 'widget/:widget_id' => 'dashboards#show_widget'
    end
  end
  
  post 'widgets' => 'widgets#show'

end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
  before_save do
    content_hash["data"].each do |x|
      x['data']['id'] ||= SecureRandom.hex(8)
    end
    self.content = content_hash.to_json
  end
  
  def content_hash
    @content_hash ||= JSON.parse(content)
  end
  
  def content= *args
    super
    @content_hash = nil
  end
  
  def sir_trevor
    @hash ||= begin
      return false unless content_hash.has_key?("data")
      content_hash["data"]
    end
  end
  
  def widget id
    content_hash["data"].select { |x| x['data']['id'] == id }.first
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :set_dashboard, only: [:show, :show_widget, :edit, :update, :destroy]

  # GET /dashboards
  # GET /dashboards.json
  def index
    @dashboards = Dashboard.all
    @preview = true
  end

  # GET /dashboards/1
  # GET /dashboards/1.json
  def show
  end
  
  def show_widget
    @widget_id = params[:widget_id]
    respond_to do |format|
      format.html { }
      format.js { render text: view_context.render_sir_trevor_block(@dashboard.widget(@widget_id)) }
    end
  end
  
  # GET /dashboards/new
  def new
    @dashboard = Dashboard.new
  end

  # GET /dashboards/1/edit
  def edit
  end

  # POST /dashboards
  # POST /dashboards.json
  def create
    @dashboard = Dashboard.new(dashboard_params)

    respond_to do |format|
      if @dashboard.save
        format.html { redirect_to @dashboard, notice: 'Dashboard was successfully created.' }
        format.json { render :show, status: :created, location: @dashboard }
      else
        format.html { render :new }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dashboards/1
  # PATCH/PUT /dashboards/1.json
  def update
    respond_to do |format|
      if @dashboard.update(dashboard_params)
        format.html { redirect_to @dashboard, notice: 'Dashboard was successfully updated.' }
        format.json { render :show, status: :ok, location: @dashboard }
      else
        format.html { render :edit }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboards/1
  # DELETE /dashboards/1.json
  def destroy
    @dashboard.destroy
    respond_to do |format|
      format.html { redirect_to dashboards_url, notice: 'Dashboard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dashboard
      @dashboard = Dashboard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dashboard_params
      params.require(:dashboard).permit!
    end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/_dashboard.html.erb
<div class="dashboard">
  <h2><%= link_to dashboard.title, dashboard %></h2>
  <%= render_sir_trevor_block dashboard.sir_trevor.first %>
</div>

app/views/dashboards/_form.html.erb
<%= bootstrap_form_for @dashboard do |f| %>
  <%= f.text_field :title %>
  <%= f.sir_trevor_text_area :content %>
  <%= f.submit %>
<% end %>

app/views/dashboards/_navbar.html.erb
<ul class="nav navbar-nav">
<% Dashboard.find_each do |d| %>
  <%= content_tag :li, class: "#{'active' if current_page? d or d == @dashboard }" do %>
    <%= link_to d.title, d %>
  <% end %>
<% end %>
</ul>

app/views/dashboards/edit.html.erb
<%= render 'form' %>

<%= button_to "delete", @dashboard, method: :delete, class: 'btn btn-danger' %> 

app/views/dashboards/index.html.erb
<div class="row">
<%= link_to 'New Dashboard', new_dashboard_path, class: 'btn btn-primary' %>
</div>

<div class="row">
<%= render @dashboards %>
</div>

app/views/dashboards/new.html.erb
<%= render 'form' %>

app/views/dashboards/show.html.erb
<div class="dashboard-header row text-right">
  <%= link_to 'Edit', edit_dashboard_path(@dashboard), class: 'btn btn-primary' %>
</div>

<div class="dashboard-content autopacked-container">
  <%= render_sir_trevor(@dashboard.content) %>
  <div class="grid-sizer col-md-2"></div>
  <div class="gutter-sizer"></div>
</div>

app/views/dashboards/show_widget.html.erb
<%= render_sir_trevor_block @dashboard.widget(@widget_id)%>